In [1]:
import pandas as pd

In [2]:
stocks = pd.read_excel("C:/Users/THE KEY/Desktop/python_datum/pandas/data/myself_data/stock/stock.xlsx")

In [3]:
stocks.shape

(60, 8)

In [4]:
stocks.head(3)

          日期    公司     收盘     开盘      高      低     交易量     涨跌幅
0 2023-02-28  BABA  87.79  88.46  89.34  87.27  24.60M -0.0164
1 2023-03-01  BABA  89.95  92.92  92.92  89.73  32.05M  0.0246
2 2023-03-02  BABA  89.75  88.96  90.92  87.97  24.02M -0.0022

In [5]:
type(stocks)

pandas.core.frame.DataFrame

In [6]:
stocks["公司"].unique()

array(['BABA', 'BAIDU', 'JD'], dtype=object)

In [7]:
stocks.index

RangeIndex(start=0, stop=60, step=1)

In [8]:
stocks.groupby("公司")["收盘"].mean()

公司
BABA      85.4430
BAIDU    141.3250
JD        42.1835
Name: 收盘, dtype: float64

### ------------------------------------------------------------

In [9]:
# Series的分层索引MulitIndex
ser = stocks.groupby(["公司","日期"])["收盘"].mean()
ser

公司     日期
BABA   2023-02-28     87.79
       2023-03-01     89.95
       2023-03-02     89.75
       2023-03-03     89.70
       2023-03-06     89.62
       2023-03-07     88.73
       2023-03-08     86.95
       2023-03-09     83.37
       2023-03-10     82.96
       2023-03-13     82.90
       2023-03-14     83.85
       2023-03-15     81.51
       2023-03-16     82.22
       2023-03-17     81.67
       2023-03-20     81.00
       2023-03-21     83.70
       2023-03-22     83.65
       2023-03-23     86.52
       2023-03-24     86.90
       2023-03-27     86.12
BAIDU  2023-02-28    134.80
       2023-03-01    145.00
       2023-03-02    141.90
       2023-03-03    149.40
       2023-03-06    147.50
       2023-03-07    144.20
       2023-03-08    139.50
       2023-03-09    137.60
       2023-03-10    129.50
       2023-03-13    134.00
       2023-03-14    129.00
       2023-03-15    133.60
       2023-03-16    125.10
       2023-03-17    142.20
       2023-03-20    143.50
       2023-03-21    148.10
       2023-03-22    146.80
       2023-03-23    150.90
       2023-03-24    154.40
       2023-03-27    149.50
JD     2023-02-28     44.44
       2023-03-01     45.73
       2023-03-02     47.07
       2023-03-03     47.46
       2023-03-06     47.92
       2023-03-07     46.57
       2023-03-08     46.98
       2023-03-09     41.68
       2023-03-10     40.47
       2023-03-13     40.11
       2023-03-14     40.44
       2023-03-15     39.34
       2023-03-16     39.79
       2023-03-17     38.83
       2023-03-20     38.66
       2023-03-21     39.54
       2023-03-22     38.50
       2023-03-23     40.07
       2023-03-24     40.29
       2023-03-27     39.78
Name: 收盘, dtype: float64

In [10]:
type(ser)

pandas.core.series.Series

In [11]:
ser.index

MultiIndex([( 'BABA', '2023-02-28'),
            ( 'BABA', '2023-03-01'),
            ( 'BABA', '2023-03-02'),
            ( 'BABA', '2023-03-03'),
            ( 'BABA', '2023-03-06'),
            ( 'BABA', '2023-03-07'),
            ( 'BABA', '2023-03-08'),
            ( 'BABA', '2023-03-09'),
            ( 'BABA', '2023-03-10'),
            ( 'BABA', '2023-03-13'),
            ( 'BABA', '2023-03-14'),
            ( 'BABA', '2023-03-15'),
            ( 'BABA', '2023-03-16'),
            ( 'BABA', '2023-03-17'),
            ( 'BABA', '2023-03-20'),
            ( 'BABA', '2023-03-21'),
            ( 'BABA', '2023-03-22'),
            ( 'BABA', '2023-03-23'),
            ( 'BABA', '2023-03-24'),
            ( 'BABA', '2023-03-27'),
            ('BAIDU', '2023-02-28'),
            ('BAIDU', '2023-03-01'),
            ('BAIDU', '2023-03-02'),
            ('BAIDU', '2023-03-03'),
            ('BAIDU', '2023-03-06'),
            ('BAIDU', '2023-03-07'),
            ('BAIDU', '2023-03-08'),
            ('BAIDU', '2023-03-09'),
            ('BAIDU', '2023-03-10'),
            ('BAIDU', '2023-03-13'),
            ('BAIDU', '2023-03-14'),
            ('BAIDU', '2023-03-15'),
            ('BAIDU', '2023-03-16'),
            ('BAIDU', '2023-03-17'),
            ('BAIDU', '2023-03-20'),
            ('BAIDU', '2023-03-21'),
            ('BAIDU', '2023-03-22'),
            ('BAIDU', '2023-03-23'),
            ('BAIDU', '2023-03-24'),
            ('BAIDU', '2023-03-27'),
            (   'JD', '2023-02-28'),
            (   'JD', '2023-03-01'),
            (   'JD', '2023-03-02'),
            (   'JD', '2023-03-03'),
            (   'JD', '2023-03-06'),
            (   'JD', '2023-03-07'),
            (   'JD', '2023-03-08'),
            (   'JD', '2023-03-09'),
            (   'JD', '2023-03-10'),
            (   'JD', '2023-03-13'),
            (   'JD', '2023-03-14'),
            (   'JD', '2023-03-15'),
            (   'JD', '2023-03-16'),
            (   'JD', '2023-03-17'),
            (   'JD', '2023-03-20'),
            (   'JD', '2023-03-21'),
            (   'JD', '2023-03-22'),
            (   'JD', '2023-03-23'),
            (   'JD', '2023-03-24'),
            (   'JD', '2023-03-27')],
           names=['公司', '日期'])

In [12]:
# unstack把二级索引变成列
ser.unstack()

日期,2023-02-28,2023-03-01,2023-03-02,2023-03-03,2023-03-06,2023-03-07,2023-03-08,2023-03-09,2023-03-10,2023-03-13,2023-03-14,2023-03-15,2023-03-16,2023-03-17,2023-03-20,2023-03-21,2023-03-22,2023-03-23,2023-03-24,2023-03-27
公司,,,,,,,,,,,,,,,,,,,,
BABA,87.79,89.95,89.75,89.70,89.62,88.73,86.95,83.37,82.96,82.90,83.85,81.51,82.22,81.67,81.00,83.70,83.65,86.52,86.90,86.12
BAIDU,134.80,145.00,141.90,149.40,147.50,144.20,139.50,137.60,129.50,134.00,129.00,133.60,125.10,142.20,143.50,148.10,146.80,150.90,154.40,149.50
JD,44.44,45.73,47.07,47.46,47.92,46.57,46.98,41.68,40.47,40.11,40.44,39.34,39.79,38.83,38.66,39.54,38.50,40.07,40.29,39.78

In [13]:
# 另一种方法
ser.reset_index()

       公司         日期      收盘
0    BABA 2023-02-28   87.79
1    BABA 2023-03-01   89.95
2    BABA 2023-03-02   89.75
3    BABA 2023-03-03   89.70
4    BABA 2023-03-06   89.62
5    BABA 2023-03-07   88.73
6    BABA 2023-03-08   86.95
7    BABA 2023-03-09   83.37
8    BABA 2023-03-10   82.96
9    BABA 2023-03-13   82.90
10   BABA 2023-03-14   83.85
11   BABA 2023-03-15   81.51
12   BABA 2023-03-16   82.22
13   BABA 2023-03-17   81.67
14   BABA 2023-03-20   81.00
15   BABA 2023-03-21   83.70
16   BABA 2023-03-22   83.65
17   BABA 2023-03-23   86.52
18   BABA 2023-03-24   86.90
19   BABA 2023-03-27   86.12
20  BAIDU 2023-02-28  134.80
21  BAIDU 2023-03-01  145.00
22  BAIDU 2023-03-02  141.90
23  BAIDU 2023-03-03  149.40
24  BAIDU 2023-03-06  147.50
25  BAIDU 2023-03-07  144.20
26  BAIDU 2023-03-08  139.50
27  BAIDU 2023-03-09  137.60
28  BAIDU 2023-03-10  129.50
29  BAIDU 2023-03-13  134.00
30  BAIDU 2023-03-14  129.00
31  BAIDU 2023-03-15  133.60
32  BAIDU 2023-03-16  125.10
33  BAIDU 2023-03-17  142.20
34  BAIDU 2023-03-20  143.50
35  BAIDU 2023-03-21  148.10
36  BAIDU 2023-03-22  146.80
37  BAIDU 2023-03-23  150.90
38  BAIDU 2023-03-24  154.40
39  BAIDU 2023-03-27  149.50
40     JD 2023-02-28   44.44
41     JD 2023-03-01   45.73
42     JD 2023-03-02   47.07
43     JD 2023-03-03   47.46
44     JD 2023-03-06   47.92
45     JD 2023-03-07   46.57
46     JD 2023-03-08   46.98
47     JD 2023-03-09   41.68
48     JD 2023-03-10   40.47
49     JD 2023-03-13   40.11
50     JD 2023-03-14   40.44
51     JD 2023-03-15   39.34
52     JD 2023-03-16   39.79
53     JD 2023-03-17   38.83
54     JD 2023-03-20   38.66
55     JD 2023-03-21   39.54
56     JD 2023-03-22   38.50
57     JD 2023-03-23   40.07
58     JD 2023-03-24   40.29
59     JD 2023-03-27   39.78

### ----------------------------------------------------------------

In [14]:
# 单层索引
ser.loc["BAIDU"]

日期
2023-02-28    134.8
2023-03-01    145.0
2023-03-02    141.9
2023-03-03    149.4
2023-03-06    147.5
2023-03-07    144.2
2023-03-08    139.5
2023-03-09    137.6
2023-03-10    129.5
2023-03-13    134.0
2023-03-14    129.0
2023-03-15    133.6
2023-03-16    125.1
2023-03-17    142.2
2023-03-20    143.5
2023-03-21    148.1
2023-03-22    146.8
2023-03-23    150.9
2023-03-24    154.4
2023-03-27    149.5
Name: 收盘, dtype: float64

In [15]:
# 多级索引，以元组的形式来筛选
ser.loc[("BAIDU","2023-03-17")]

142.2

In [16]:
# 直接筛选第二级的索引
ser.loc[:,"2023-03-17"]

公司
BABA      81.67
BAIDU    142.20
JD        38.83
Name: 收盘, dtype: float64

### ---------------------------------------------------------------

In [17]:
# DataFrame的索引
stocks.set_index(["公司","日期"], inplace = True)
# 执行一次就设置成索引了，再执行就错了

In [19]:
stocks.sort_index(inplace = True)
stocks

                      收盘      开盘       高       低     交易量     涨跌幅
公司    日期
BABA  2023-02-28   87.79   88.46   89.34   87.27  24.60M -0.0164
      2023-03-01   89.95   92.92   92.92   89.73  32.05M  0.0246
      2023-03-02   89.75   88.96   90.92   87.97  24.02M -0.0022
      2023-03-03   89.70   90.09   90.39   88.43  25.83M -0.0006
      2023-03-06   89.62   89.58   91.30   88.03  16.98M -0.0009
      2023-03-07   88.73   89.52   90.05   88.20  14.51M -0.0099
      2023-03-08   86.95   87.39   87.77   86.45  14.72M -0.0201
      2023-03-09   83.37   85.12   85.69   82.88  24.12M -0.0412
      2023-03-10   82.96   82.64   84.52   82.33  18.12M -0.0049
      2023-03-13   82.90   83.01   83.75   81.97  17.62M -0.0007
      2023-03-14   83.85   82.86   83.91   82.16  19.05M  0.0115
      2023-03-15   81.51   81.55   82.54   80.15  20.86M -0.0279
      2023-03-16   82.22   81.46   82.48   80.66  22.41M  0.0087
      2023-03-17   81.67   84.00   84.16   80.62  23.71M -0.0067
      2023-03-20   81.00   80.15   81.90   79.48  18.95M -0.0082
      2023-03-21   83.70   82.46   84.09   82.00  16.44M  0.0333
      2023-03-22   83.65   84.84   85.39   83.51  21.08M -0.0006
      2023-03-23   86.52   87.68   88.38   85.26  26.79M  0.0343
      2023-03-24   86.90   85.87   88.11   85.63  20.35M  0.0044
      2023-03-27   86.12   87.13   88.22   85.50  18.18M -0.0090
BAIDU 2023-02-28  134.80  137.00  138.50  134.00  12.43M  0.0060
      2023-03-01  145.00  135.00  146.90  135.00  17.88M  0.0757
      2023-03-02  141.90  141.00  142.60  139.40  16.49M -0.0214
      2023-03-03  149.40  148.30  150.80  146.60  13.38M  0.0529
      2023-03-06  147.50  149.40  150.00  145.70   9.97M -0.0127
      2023-03-07  144.20  147.50  149.30  142.30   9.00M -0.0224
      2023-03-08  139.50  141.10  141.50  137.60   7.68M -0.0326
      2023-03-09  137.60  140.00  141.00  137.40   6.51M -0.0136
      2023-03-10  129.50  128.20  131.10  128.00  20.86M -0.0589
      2023-03-13  134.00  131.50  136.70  129.00  11.66M  0.0347
      2023-03-14  129.00  132.30  134.00  128.50   8.23M -0.0373
      2023-03-15  133.60  134.50  138.30  133.00  14.63M  0.0357
      2023-03-16  125.10  131.30  134.40  120.10  24.31M -0.0636
      2023-03-17  142.20  135.00  146.00  134.00  32.59M  0.1367
      2023-03-20  143.50  146.50  148.00  141.70  16.03M  0.0091
      2023-03-21  148.10  146.20  149.30  143.50  13.13M  0.0321
      2023-03-22  146.80  147.90  149.80  145.80   8.86M -0.0088
      2023-03-23  150.90  145.50  151.10  144.50  12.34M  0.0279
      2023-03-24  154.40  148.50  159.00  148.00  25.84M  0.0232
      2023-03-27  149.50  156.90  157.00  147.40  15.52M -0.0317
JD    2023-02-28   44.44   44.28   45.11   43.97   6.44M -0.0067
      2023-03-01   45.73   46.54   46.77   45.30   9.24M  0.0290
      2023-03-02   47.07   45.62   47.15   45.40   7.90M  0.0293
      2023-03-03   47.46   47.36   48.22   47.32   7.87M  0.0083
      2023-03-06   47.92   47.67   48.72   47.23   7.17M  0.0097
      2023-03-07   46.57   47.36   47.36   46.34   6.51M -0.0282
      2023-03-08   46.98   45.51   47.41   45.47   8.51M  0.0088
      2023-03-09   41.68   44.51   44.79   41.31  37.10M -0.1128
      2023-03-10   40.47   40.88   41.38   40.07  15.48M -0.0290
      2023-03-13   40.11   39.68   40.84   39.04  13.14M -0.0089
      2023-03-14   40.44   39.98   40.81   39.46  10.78M  0.0082
      2023-03-15   39.34   39.38   39.88   38.81  10.40M -0.0272
      2023-03-16   39.79   39.07   40.09   38.91   9.83M  0.0114
      2023-03-17   38.83   39.48   39.67   38.57  11.48M -0.0241
      2023-03-20   38.66   38.00   39.30   37.70  11.16M -0.0044
      2023-03-21   39.54   38.62   39.59   38.43   9.71M  0.0228
      2023-03-22   38.50   39.50   39.87   38.50   8.27M -0.0263
      2023-03-23   40.07   40.30   40.89   39.63  11.04M  0.0408
      2023-03-24   40.29   39.92   40.84   39.85   7.35M  0.0055
      2023-03-27   39.78   39.34   39.96   39.15   7.31M -0.0127

In [20]:
stocks.index

MultiIndex([( 'BABA', '2023-02-28'),
            ( 'BABA', '2023-03-01'),
            ( 'BABA', '2023-03-02'),
            ( 'BABA', '2023-03-03'),
            ( 'BABA', '2023-03-06'),
            ( 'BABA', '2023-03-07'),
            ( 'BABA', '2023-03-08'),
            ( 'BABA', '2023-03-09'),
            ( 'BABA', '2023-03-10'),
            ( 'BABA', '2023-03-13'),
            ( 'BABA', '2023-03-14'),
            ( 'BABA', '2023-03-15'),
            ( 'BABA', '2023-03-16'),
            ( 'BABA', '2023-03-17'),
            ( 'BABA', '2023-03-20'),
            ( 'BABA', '2023-03-21'),
            ( 'BABA', '2023-03-22'),
            ( 'BABA', '2023-03-23'),
            ( 'BABA', '2023-03-24'),
            ( 'BABA', '2023-03-27'),
            ('BAIDU', '2023-02-28'),
            ('BAIDU', '2023-03-01'),
            ('BAIDU', '2023-03-02'),
            ('BAIDU', '2023-03-03'),
            ('BAIDU', '2023-03-06'),
            ('BAIDU', '2023-03-07'),
            ('BAIDU', '2023-03-08'),
            ('BAIDU', '2023-03-09'),
            ('BAIDU', '2023-03-10'),
            ('BAIDU', '2023-03-13'),
            ('BAIDU', '2023-03-14'),
            ('BAIDU', '2023-03-15'),
            ('BAIDU', '2023-03-16'),
            ('BAIDU', '2023-03-17'),
            ('BAIDU', '2023-03-20'),
            ('BAIDU', '2023-03-21'),
            ('BAIDU', '2023-03-22'),
            ('BAIDU', '2023-03-23'),
            ('BAIDU', '2023-03-24'),
            ('BAIDU', '2023-03-27'),
            (   'JD', '2023-02-28'),
            (   'JD', '2023-03-01'),
            (   'JD', '2023-03-02'),
            (   'JD', '2023-03-03'),
            (   'JD', '2023-03-06'),
            (   'JD', '2023-03-07'),
            (   'JD', '2023-03-08'),
            (   'JD', '2023-03-09'),
            (   'JD', '2023-03-10'),
            (   'JD', '2023-03-13'),
            (   'JD', '2023-03-14'),
            (   'JD', '2023-03-15'),
            (   'JD', '2023-03-16'),
            (   'JD', '2023-03-17'),
            (   'JD', '2023-03-20'),
            (   'JD', '2023-03-21'),
            (   'JD', '2023-03-22'),
            (   'JD', '2023-03-23'),
            (   'JD', '2023-03-24'),
            (   'JD', '2023-03-27')],
           names=['公司', '日期'])

### -----------------------------------------------------------------

**重要知识**,在选择数据时：
- 元组(key1,key2)代表筛选多层索引，其中key1是索引第一级，key2是第二级，例如key1=JD,key2=2023/3/27
- 列表[key1,key2]代表同一层的多个key，其中key1和key2是并列的同级索引，比如key1=JD,key2=BAIDU

In [21]:
stocks.loc["JD"].head(3)

               收盘     开盘      高      低    交易量     涨跌幅
日期
2023-02-28  44.44  44.28  45.11  43.97  6.44M -0.0067
2023-03-01  45.73  46.54  46.77  45.30  9.24M  0.0290
2023-03-02  47.07  45.62  47.15  45.40  7.90M  0.0293

In [22]:
stocks.loc[("JD","2023-03-08"),:]

收盘      46.98
开盘      45.51
高       47.41
低       45.47
交易量     8.51M
涨跌幅    0.0088
Name: (JD, 2023-03-08 00:00:00), dtype: object

In [23]:
stocks.loc[("JD","2023-03-08"),"交易量"]

'8.51M'

In [24]:
# 并列的
stocks.loc[["BAIDU","JD"],:]

                      收盘      开盘       高       低     交易量     涨跌幅
公司    日期
BAIDU 2023-02-28  134.80  137.00  138.50  134.00  12.43M  0.0060
      2023-03-01  145.00  135.00  146.90  135.00  17.88M  0.0757
      2023-03-02  141.90  141.00  142.60  139.40  16.49M -0.0214
      2023-03-03  149.40  148.30  150.80  146.60  13.38M  0.0529
      2023-03-06  147.50  149.40  150.00  145.70   9.97M -0.0127
      2023-03-07  144.20  147.50  149.30  142.30   9.00M -0.0224
      2023-03-08  139.50  141.10  141.50  137.60   7.68M -0.0326
      2023-03-09  137.60  140.00  141.00  137.40   6.51M -0.0136
      2023-03-10  129.50  128.20  131.10  128.00  20.86M -0.0589
      2023-03-13  134.00  131.50  136.70  129.00  11.66M  0.0347
      2023-03-14  129.00  132.30  134.00  128.50   8.23M -0.0373
      2023-03-15  133.60  134.50  138.30  133.00  14.63M  0.0357
      2023-03-16  125.10  131.30  134.40  120.10  24.31M -0.0636
      2023-03-17  142.20  135.00  146.00  134.00  32.59M  0.1367
      2023-03-20  143.50  146.50  148.00  141.70  16.03M  0.0091
      2023-03-21  148.10  146.20  149.30  143.50  13.13M  0.0321
      2023-03-22  146.80  147.90  149.80  145.80   8.86M -0.0088
      2023-03-23  150.90  145.50  151.10  144.50  12.34M  0.0279
      2023-03-24  154.40  148.50  159.00  148.00  25.84M  0.0232
      2023-03-27  149.50  156.90  157.00  147.40  15.52M -0.0317
JD    2023-02-28   44.44   44.28   45.11   43.97   6.44M -0.0067
      2023-03-01   45.73   46.54   46.77   45.30   9.24M  0.0290
      2023-03-02   47.07   45.62   47.15   45.40   7.90M  0.0293
      2023-03-03   47.46   47.36   48.22   47.32   7.87M  0.0083
      2023-03-06   47.92   47.67   48.72   47.23   7.17M  0.0097
      2023-03-07   46.57   47.36   47.36   46.34   6.51M -0.0282
      2023-03-08   46.98   45.51   47.41   45.47   8.51M  0.0088
      2023-03-09   41.68   44.51   44.79   41.31  37.10M -0.1128
      2023-03-10   40.47   40.88   41.38   40.07  15.48M -0.0290
      2023-03-13   40.11   39.68   40.84   39.04  13.14M -0.0089
      2023-03-14   40.44   39.98   40.81   39.46  10.78M  0.0082
      2023-03-15   39.34   39.38   39.88   38.81  10.40M -0.0272
      2023-03-16   39.79   39.07   40.09   38.91   9.83M  0.0114
      2023-03-17   38.83   39.48   39.67   38.57  11.48M -0.0241
      2023-03-20   38.66   38.00   39.30   37.70  11.16M -0.0044
      2023-03-21   39.54   38.62   39.59   38.43   9.71M  0.0228
      2023-03-22   38.50   39.50   39.87   38.50   8.27M -0.0263
      2023-03-23   40.07   40.30   40.89   39.63  11.04M  0.0408
      2023-03-24   40.29   39.92   40.84   39.85   7.35M  0.0055
      2023-03-27   39.78   39.34   39.96   39.15   7.31M -0.0127

In [25]:
stocks.loc[(["JD","BAIDU"],"2023-03-08"),:]

                      收盘      开盘       高       低    交易量     涨跌幅
公司    日期
JD    2023-03-08   46.98   45.51   47.41   45.47  8.51M  0.0088
BAIDU 2023-03-08  139.50  141.10  141.50  137.60  7.68M -0.0326

In [26]:
stocks.loc[(["JD","BAIDU"],"2023-03-08"),'涨跌幅']

公司     日期
JD     2023-03-08    0.0088
BAIDU  2023-03-08   -0.0326
Name: 涨跌幅, dtype: float64

In [27]:
stocks.loc[('BABA',["2023-02-28","2023-03-27"]),:]

                    收盘     开盘      高      低     交易量     涨跌幅
公司   日期
BABA 2023-02-28  87.79  88.46  89.34  87.27  24.60M -0.0164
     2023-03-27  86.12  87.13  88.22  85.50  18.18M -0.0090

In [28]:
# slice(None)可以筛选出这一索引的所有内容
stocks.loc[(slice(None),["2023-03-16","2023-03-17"]),:]

                      收盘      开盘       高       低     交易量     涨跌幅
公司    日期
BABA  2023-03-16   82.22   81.46   82.48   80.66  22.41M  0.0087
      2023-03-17   81.67   84.00   84.16   80.62  23.71M -0.0067
BAIDU 2023-03-16  125.10  131.30  134.40  120.10  24.31M -0.0636
      2023-03-17  142.20  135.00  146.00  134.00  32.59M  0.1367
JD    2023-03-16   39.79   39.07   40.09   38.91   9.83M  0.0114
      2023-03-17   38.83   39.48   39.67   38.57  11.48M -0.0241

In [29]:
# 可以重置索引，把它变成普通的列
stocks.reset_index()

       公司         日期      收盘      开盘       高       低     交易量     涨跌幅
0    BABA 2023-02-28   87.79   88.46   89.34   87.27  24.60M -0.0164
1    BABA 2023-03-01   89.95   92.92   92.92   89.73  32.05M  0.0246
2    BABA 2023-03-02   89.75   88.96   90.92   87.97  24.02M -0.0022
3    BABA 2023-03-03   89.70   90.09   90.39   88.43  25.83M -0.0006
4    BABA 2023-03-06   89.62   89.58   91.30   88.03  16.98M -0.0009
5    BABA 2023-03-07   88.73   89.52   90.05   88.20  14.51M -0.0099
6    BABA 2023-03-08   86.95   87.39   87.77   86.45  14.72M -0.0201
7    BABA 2023-03-09   83.37   85.12   85.69   82.88  24.12M -0.0412
8    BABA 2023-03-10   82.96   82.64   84.52   82.33  18.12M -0.0049
9    BABA 2023-03-13   82.90   83.01   83.75   81.97  17.62M -0.0007
10   BABA 2023-03-14   83.85   82.86   83.91   82.16  19.05M  0.0115
11   BABA 2023-03-15   81.51   81.55   82.54   80.15  20.86M -0.0279
12   BABA 2023-03-16   82.22   81.46   82.48   80.66  22.41M  0.0087
13   BABA 2023-03-17   81.67   84.00   84.16   80.62  23.71M -0.0067
14   BABA 2023-03-20   81.00   80.15   81.90   79.48  18.95M -0.0082
15   BABA 2023-03-21   83.70   82.46   84.09   82.00  16.44M  0.0333
16   BABA 2023-03-22   83.65   84.84   85.39   83.51  21.08M -0.0006
17   BABA 2023-03-23   86.52   87.68   88.38   85.26  26.79M  0.0343
18   BABA 2023-03-24   86.90   85.87   88.11   85.63  20.35M  0.0044
19   BABA 2023-03-27   86.12   87.13   88.22   85.50  18.18M -0.0090
20  BAIDU 2023-02-28  134.80  137.00  138.50  134.00  12.43M  0.0060
21  BAIDU 2023-03-01  145.00  135.00  146.90  135.00  17.88M  0.0757
22  BAIDU 2023-03-02  141.90  141.00  142.60  139.40  16.49M -0.0214
23  BAIDU 2023-03-03  149.40  148.30  150.80  146.60  13.38M  0.0529
24  BAIDU 2023-03-06  147.50  149.40  150.00  145.70   9.97M -0.0127
25  BAIDU 2023-03-07  144.20  147.50  149.30  142.30   9.00M -0.0224
26  BAIDU 2023-03-08  139.50  141.10  141.50  137.60   7.68M -0.0326
27  BAIDU 2023-03-09  137.60  140.00  141.00  137.40   6.51M -0.0136
28  BAIDU 2023-03-10  129.50  128.20  131.10  128.00  20.86M -0.0589
29  BAIDU 2023-03-13  134.00  131.50  136.70  129.00  11.66M  0.0347
30  BAIDU 2023-03-14  129.00  132.30  134.00  128.50   8.23M -0.0373
31  BAIDU 2023-03-15  133.60  134.50  138.30  133.00  14.63M  0.0357
32  BAIDU 2023-03-16  125.10  131.30  134.40  120.10  24.31M -0.0636
33  BAIDU 2023-03-17  142.20  135.00  146.00  134.00  32.59M  0.1367
34  BAIDU 2023-03-20  143.50  146.50  148.00  141.70  16.03M  0.0091
35  BAIDU 2023-03-21  148.10  146.20  149.30  143.50  13.13M  0.0321
36  BAIDU 2023-03-22  146.80  147.90  149.80  145.80   8.86M -0.0088
37  BAIDU 2023-03-23  150.90  145.50  151.10  144.50  12.34M  0.0279
38  BAIDU 2023-03-24  154.40  148.50  159.00  148.00  25.84M  0.0232
39  BAIDU 2023-03-27  149.50  156.90  157.00  147.40  15.52M -0.0317
40     JD 2023-02-28   44.44   44.28   45.11   43.97   6.44M -0.0067
41     JD 2023-03-01   45.73   46.54   46.77   45.30   9.24M  0.0290
42     JD 2023-03-02   47.07   45.62   47.15   45.40   7.90M  0.0293
43     JD 2023-03-03   47.46   47.36   48.22   47.32   7.87M  0.0083
44     JD 2023-03-06   47.92   47.67   48.72   47.23   7.17M  0.0097
45     JD 2023-03-07   46.57   47.36   47.36   46.34   6.51M -0.0282
46     JD 2023-03-08   46.98   45.51   47.41   45.47   8.51M  0.0088
47     JD 2023-03-09   41.68   44.51   44.79   41.31  37.10M -0.1128
48     JD 2023-03-10   40.47   40.88   41.38   40.07  15.48M -0.0290
49     JD 2023-03-13   40.11   39.68   40.84   39.04  13.14M -0.0089
50     JD 2023-03-14   40.44   39.98   40.81   39.46  10.78M  0.0082
51     JD 2023-03-15   39.34   39.38   39.88   38.81  10.40M -0.0272
52     JD 2023-03-16   39.79   39.07   40.09   38.91   9.83M  0.0114
53     JD 2023-03-17   38.83   39.48   39.67   38.57  11.48M -0.0241
54     JD 2023-03-20   38.66   38.00   39.30   37.70  11.16M -0.0044
55     JD 2023-03-21   39.54   38.62   39.59   38.43   9.71M  0.0228
56     JD 2023-03-22   38.50   39.50   39.87   38.50   8.27M -0.0263
57     JD 2023-03-23   40.07   40.30   40.89   39.63  11.04M  0.0408
58     JD 2023-03-24   40.29   39.92   40.84   39.85   7.35M  0.0055
59     JD 2023-03-27   39.78   39.34   39.96   39.15   7.31M -0.0127